export const WAIT_INTERVAL = 250;
export const LOCATION_RADIUS = 400;
export const LOCATION_UPDATE_TIME_INTERVAL = 60000;
export const LOCATION_UPDATE_DISTANCE_INTERVAL = 100;
export const LOCATION_UPDATES = 'DEVICE_LOCATION_UPDATES';
